# #！/bin/bash
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_IHC/drug_immunesig_IHC_GSEA_result
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_IHC/drug_immunesig_IHC_GSEA_result_978genes

rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_CPE/drug_immunesig_CPE_GSEA_result
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_CPE/drug_immunesig_CPE_GSEA_result_978genes




# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/70138/



# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/BRCA_BRCA.Basal/

# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/BRCA_Primary/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/COAD_Primary/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/LIHC_Primary/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/LUAD_Primary/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/LUSC_Primary/

# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/READ_MSI/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/READ_MSI-L/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/READ_Primary/

# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/SKCM_Metastatic/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/SKCM_Primary/

# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/STAD_Primary/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/UCEC_Primary/


# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/BRCA
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/COAD
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/LIHC
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/LUAD
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/LUAD_Primary
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/LUSC
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/OV
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/READ
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/SKCM
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/SKCM_Primary
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/STAD
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/UCEC
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result_978genes/92742/UCEC_Primary

