#!/bin/bash
# delete GSEA direct datafiles 
# 1) delete big error files 
rm -rf /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/COAD_MSI/
rm -rf /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/READ_MSI/

# delete raw GSEA files for all_400 genes (union of positive-related and negative-related genes)
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/BRCA_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/COAD_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/LUAD_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/PAAD_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/PRAD_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/READ_MSI-L/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/READ_MSS/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/READ_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/70138/SKCM_Metastatic/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/BRCA_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/COAD_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/LUSC_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/OV_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/READ_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/SKCM_Metastatic/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/STAD_Primary/all_400/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_TUMERIC/drug_immunesig_TUMERIC_GSEA_result/92742/UCEC_Primary/all_400/

# delete raw GSEA files for other tumor purity

rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_CPE/drug_immunesig_CPE_GSEA_result/70138/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_CPE/drug_immunesig_CPE_GSEA_result/92742/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_CPE/drug_immunesig_CPE_GSEA_result_978genes/70138/
rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_CPE/drug_immunesig_CPE_GSEA_result_978genes/92742/

# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_IHC/drug_immunesig_IHC_GSEA_result/70138/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_IHC/drug_immunesig_IHC_GSEA_result/92742/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_IHC/drug_immunesig_IHC_GSEA_result_978genes/70138/
# rm -r /picb/bigdata/project/FengFYM/p2_1_immunotherapy_targetedtherapy/r1_drug_immuneSig_correlation_analysis/03_drug_immuneSig_enrichment/results_IHC/drug_immunesig_IHC_GSEA_result_978genes/92742/
